### ISSUE TITLE
获取id错误

### ISSUE THREAD

**Issue by 2780qq** [Solana0x/Query_Id#1]
![image](https://github.com/user-attachments/assets/0f2d3dc4-8897-4b86-a1fb-fa576ab79175)

**Comment by Solana0x** [comment]
请在所有字段中添加详细信息 

如名称、链接、详细信息等，添加它并一次又一次地尝试！

**Comment by Solana0x** [comment]
不用担心，您可以添加随机详细信息，也可以检查 google，那里有人展示了如何创建 api id 和哈希值

**Comment by 2780qq** [comment]
试过了这个还是不行一直显示错误

**Comment by Solana0x** [comment]
是的，我知道 Telegram 网站有问题，只需搜索谷歌即可！

就像你必须在每个地方都使用小盒子添加字母数字添加项目的详细信息**随机网站添加并重试它将起作用或从谷歌获取任何随机详细信息并添加它

**Comment by 2780qq** [comment]
我也尝试了还是这样 很困惑

**Comment by Solana0x** [comment]
我想说再试一次是唯一的选择，否则你也可以为机器人手动一一获取查询ID
