### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by Mostaphadartagnan** [Solana0x/Query_Id#10]
hello, i could not login with phone number, i did not get any OTP message .. 

and did not know how to login via telegram session string or API hash ... 

help me please

**Comment by AntiWarforever** [comment]
> hello, i could not login with phone number, i did not get any OTP message ..
> 
> and did not know how to login via telegram session string or API hash ...
> 
> help me please

Use vpn otp don't have problem (if you update last requirement)

**Comment by AntiWarforever** [comment]
> > hello, i could not login with phone number, i did not get any OTP message ..
> > and did not know how to login via telegram session string or API hash ...
> > help me please
> 
> Use vpn OTP don't have problem (if you update last requirement)
