### ISSUE TITLE
Kenapa setiap saya login menggunakan number dan membuat session, telegram saya otomatis keluar sendiri?? Dan saya tidak bisa login dan mendapatkan akun telegram saya kembali

### ISSUE THREAD

**Issue by goldsfinder** [Solana0x/Query_Id#2]

**Comment by 0xsiwant** [comment]
same issues

**Comment by Solana0x** [comment]
Please dont use the New telegram accounts @goldsfinder The api id and hash method is risky these days telegram will ban you if you dont use quality proxies or do mass Multi accounting ! the above method is for those who have either old accounts or have a Good Quality of proxies !
