### ISSUE TITLE
Additional Suggestion: Using Lonami for New Telegram Accounts

### ISSUE THREAD

**Issue by 0xsiwant** [Solana0x/Query_Id#3]
I have tried requesting query_id and user_id, but the results obtained from the script do not match what appears in Inspect Element -> Application -> Session Storage -> query_id. I have also tried this on several other bots, but often the generated token, query, or user is invalid.

Additional Suggestion:
Using .session on a new Telegram account is highly risky and could lead to a ban. As an alternative, I suggest using lonami, which is safer and more stable for creating sessions on new accounts. With lonami, session management is improved, reducing the risk of bans or errors during login.

**Comment by Solana0x** [comment]
Well older accounts doesnt gets banned too easy and secondly everytime you would login a new Query id is generated So it doesnt matters if the Query id isnt same while inspect or by bot script ! they wont be even same ever !

hash always changes !

-> **User is invalid**  - I tried in all of the Bot you can try my blum script and use the user id there ! every bot have diff user id so the code that i have published is well tested and works with all kinds of bots !

-> If you wanted you can use it else you can manually write one by one by !! i just made the script for the usage :) not forced anyone to use my methods there are several other ways to do farm airdrops
