### ISSUE TITLE
Coub query

### ISSUE THREAD

**Issue by AntiWarforever** [Solana0x/Query_Id#7]
Why some bots do not give query with this tool
like (coub)
Do we need to do something special?

**Comment by Solana0x** [comment]
can you please name those bot i will check them personally

**Comment by AntiWarforever** [comment]
> can you please name those bot i will check them personally

It seems that all web requests no longer give me a query If they give it, it starts from the user id Like @coub and @BabyDogePAWS_Bot Will you check please?

**Comment by Solana0x** [comment]
these are working please try again :)

**Comment by AntiWarforever** [comment]
> these are working please try again :)

It does not give you the query_id itself
& output starts with user_id?(Is there a query_id in your output?)
