### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by AntiWarforever** [Solana0x/Query_Id#8]
When we define the name of a session from letters
When we want to get a query from that session, it creates the file name only from the numbers inside the name

```
Processing account: mynew_sess_75
WebView result saved to webview_results\75.txt
```
must be mynew_sess_75.txt
but
output file > 75.txt 

& please can make a setting to enable and disable
that all the data and queries are placed in one file in a row?
 like:
user=%7B%22id%22%3A74844454507%2C%22first_name%2........
user=%7B%22id%22%3A7484434507%2C%22first_name%2........
user=%7B%22id%22%3A7481334507%2C%22first_name%2........
thanks again ...

**Comment by Solana0x** [comment]
ok

**Comment by AntiWarforever** [comment]
> ok

I have another trouble for you😁❤️
It can increase safty for every request with random agent
